; PlatformIO Project Configuration File
[platformio]
extra_configs = secrets.ini

[env:nanoatmega328]
platform = atmelavr
board = nanoatmega328
framework = arduino
upload_speed = 115200
lib_deps = 
    Chris--A/Keypad @ ^3.1.1